include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

linter:
  rules:
    - prefer_const_constructors

dart_code_metrics:
  rules:
    - newline-before-return
  metrics-exclude:
    - test/**

  metrics:
    cyclomatic-complexity: 20
    number-of-arguments: 4
    maximum-nesting-level: 5
    source-lines-of-code: 100