name: bookara
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_native_splash: ^2.0.0
  responsive_sizer: ^3.3.1
  get_storage: ^2.1.1
  animations: ^2.0.11
  flutter_svg: ^2.1.0
  circle_nav_bar: ^2.2.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1
  flutter_background_service: ^5.0.4
  permission_handler: ^12.0.0+1
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  dotenv: ^4.2.0
  flutter_dotenv: ^5.2.1
  loading_animation_widget: ^1.3.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FF3B30"
  image: "assets/images/i_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env.prod
    - .env.dev
