class AppContent {
  static const String appName = 'app_name';
  static const String login = 'login';
  static const String logout = 'logout';
  static const String email = 'email';
  static const String password = 'password';
  static const String signUp = 'sign_up';
  static const String forgotPassword = 'forgot_password';
  static const String home = 'home';
  static const String category = 'category';
  static const String library = 'library';
  static const String chapters = 'chapters';
  static const String readNow = 'read_now';
  static const String favorite = 'favorite';
  static const String settings = 'settings';
  static const String changeLanguage = 'change_language';
  static const String profile = 'profile';
  static const String errorOccurred = 'error_occurred';
  static const String back = 'back';
  static const String continueReading = 'continue_reading';
  static const String language = 'Ngôn ngữ';
  static const String languageVietnamese = 'Tiếng Việt';
  static const String languageEnglish = 'Tiếng Anh';
  static const String countryVietnam = 'Việt Nam';
  static const String theme = 'Chủ đề';
  static const String selectThem = 'Chọn chủ đề';
  static const String darkMode = 'chế độ ban đêm';
  static const String dark = 'Ban đêm';
}
