// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtvv7NCzuFRZN4aLhfWzPUiX6tijwi4cE',
    appId: '1:35644670840:web:5cb46a19adb7ac84e67e8d',
    messagingSenderId: '35644670840',
    projectId: 'bookara-cfa06',
    authDomain: 'bookara-cfa06.firebaseapp.com',
    storageBucket: 'bookara-cfa06.firebasestorage.app',
    measurementId: 'G-EKRQDRRMHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkrmxbVZknTfS6B6gTvVczLtN0NquaCos',
    appId: '1:35644670840:android:329899393b163ae4e67e8d',
    messagingSenderId: '35644670840',
    projectId: 'bookara-cfa06',
    storageBucket: 'bookara-cfa06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2EIPJVoBc2AD-ciN4Lan6ogBrORkjKPs',
    appId: '1:35644670840:ios:fcd420821fd0c999e67e8d',
    messagingSenderId: '35644670840',
    projectId: 'bookara-cfa06',
    storageBucket: 'bookara-cfa06.firebasestorage.app',
    androidClientId: '35644670840-qo48n607regsdgbpehn24ljd3us902ja.apps.googleusercontent.com',
    iosClientId: '35644670840-tkqm0cid2d8hcnnpf90mnso1jt6o72km.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2EIPJVoBc2AD-ciN4Lan6ogBrORkjKPs',
    appId: '1:35644670840:ios:fcd420821fd0c999e67e8d',
    messagingSenderId: '35644670840',
    projectId: 'bookara-cfa06',
    storageBucket: 'bookara-cfa06.firebasestorage.app',
    androidClientId: '35644670840-qo48n607regsdgbpehn24ljd3us902ja.apps.googleusercontent.com',
    iosClientId: '35644670840-tkqm0cid2d8hcnnpf90mnso1jt6o72km.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtvv7NCzuFRZN4aLhfWzPUiX6tijwi4cE',
    appId: '1:35644670840:web:04f770db7f13575ae67e8d',
    messagingSenderId: '35644670840',
    projectId: 'bookara-cfa06',
    authDomain: 'bookara-cfa06.firebaseapp.com',
    storageBucket: 'bookara-cfa06.firebasestorage.app',
    measurementId: 'G-8EZVQ33TVS',
  );
}
